# Hardware-specific configuration - GENERATED by vm-setup-generator.sh
# DO NOT EDIT MANUALLY - this file gets regenerated
{ config, pkgs, lib, ... }:

{
  # Essential boot configuration for VM
  boot.loader.grub = {
    enable = true;
    device = "/dev/vda";
    timeout = 1;
  };
  
  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" "af_packet" ];

  # File systems
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
    autoResize = true;
  };

  # Network configuration - basic setup
  networking = {
    useDHCP = false;
    
    # Test interface for QEMU user networking
    interfaces.eth0 = {
      useDHCP = true;
    };
    
    firewall = {
      enable = true;
      allowPing = true;
    };
  };

  # VM specific configuration for testing
  virtualisation.vmVariant = {
    virtualisation = {
      memorySize = 2048;
      cores = 2;
      graphics = false;
      qemu.options = [
        "-nographic"
        "-serial mon:stdio"
      ];
    };
  };
}
